name: timml

on:
  # Trigger the workflow on push or pull request on master
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install uv with Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras

      - name: ruff-lint
        run: uv run ruff check

      - name: ruff-format
        run: uv run ruff format --check

      - name: Run tests
        run: uv run pytest -v ./tests

      - name: Numba coverage
        run: |
          NUMBA_DISABLE_JIT=1 uv run pytest --cov-append ./tests/test_besselaes.py

      - name: Test tutorial notebooks
        run: |
          uv run pytest --nbval --cov-append --dist loadscope -n auto docs/00tutorials/
    
      - name: Test example notebooks
        run: |
          uv run pytest --nbval --cov-append --dist loadscope -n auto docs/03examples/

      - name: Test cross-section notebooks
        run: |
          uv run pytest --nbval --cov-append --dist loadscope -n auto docs/04xsections/

      - name: Test other notebooks
        run: |
          uv run pytest --nbval --cov-append --dist loadscope -n auto notebooks/large_diameter_experimental.ipynb notebooks/timml_besselaesnew_test.ipynb

